### ISSUE TITLE
novendor: include go generate related vendor packages

### ISSUE THREAD

**Issue by gdearment** [palantir/godel#156]
Currently `check novendor` will flag dependencies that are required by code run as part of `generate` tasks. It would be nice if these vendored packages could be accounted for as part of the `novendor` and `extimport` to make it possible to vendor generation libraries.

**Comment by nmiyake** [comment]
Unfortunately this would probably require parsing the content of `go generate` and then inferring the dependency tree of those packages. I can't think of a generic way to do this, and don't know if using a heuristic-based approach is worth it... Although it's unsatisfying, currently the suggested work-around is to add exclusions to the `checks.yml` configuration to have `novendor` ignore packages that exist only for running projects locally.

Another option is to handle this at a code organization perspective -- you can have a subdirectory (`internal` or `supporting` etc.) that has its own `vendor` directory just for code vendored only for the purposes of running tasks, and then put that entire directory in `exclude.yml` to exclude it from all checks.

**Comment by gdearment** [comment]
How would i add the exclusion to the check.yml. Tried doing:
```
novendor:
    args:
      # Exclude package
      - "-ignore"
      - "github.com/gdearment/project/vendor/github.com/palantir/pkg"
```

and saw:
```
./godelw check novendor
Running novendor...
Unknown flag -ignore

NAME:
    -

USAGE:
    [global flags] command [command flags]

GLOBAL FLAGS:
   --debug            Run in debug mode (print full stack traces on
                      failures and include other debugging output)
                      (default=$DEBUG_CLI)
   --project-package  use the 'project' paradigm to interpret packages
                      and only output projects that are unused
   --full, -f         include full path of unused packages (default
                      omits path to vendor directory)
 * <pkgs>             paths to the packages to check
   --print-pkg-info   print all project packages and vendored packages
                      that are found before execution
   --version          print version and exit
   --help, -h         print help and exit

```

**Comment by gdearment** [comment]
nevermind, figured it out:
```
novendor:
    filters:
      # dependencies for conjure-go, which is vendored for go generate but not referenced directly
      - value: "github.com/danverbraganza/varcaser"
      - value: "github.com/mitchellh/go-wordwrap"
      - value: "github.com/nmiyake/pkg"
      - value: "github.com/palantir/checks"
      - value: "github.com/palantir/goastwriter"
      - value: "github.com/palantir/pkg"
      - value: "github.com/pkg/errors"
      - value: "github.com/termie/go-shutil"
      - value: "golang.org/x/crypto"
      - value: "golang.org/x/text"
      - value: "golang.org/x/tools"
      - value: "gopkg.in/yaml.v2"
```
