### ISSUE TITLE
gunit: default test behavior does not work properly if a tag key contains capitalization

### ISSUE THREAD

**Issue by nmiyake** [palantir/godel#167]
If a test key is capitalized, running tests without tags does not work properly.

Configuration like this works:

```
tags:
  integration:
    names:
      - "^integration$"
```

In this case, running `./godelw test` will run all test except those matching `^integration$`.

However, if the same configuration key contains capitalization:

```
tags:
  Integration:
    names:
      - "^integration$"
```

Then this no longer works -- running `./godelw test` runs all tests (it does not exclude the tests that match the tags). This is true for all tags if any key contains capitalization.
